import { firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-app.js';
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-auth.js';
import { getFirestore, collection, getDocs, doc, writeBatch, serverTimestamp, addDoc } from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js';
import { getStorage, ref, uploadBytes, getDownloadURL } from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-storage.js';

const WEEKS=['Apr W1','Apr W2','Apr W3','Apr W4','May W1','May W2','May W3','May W4','Jun W1','Jun W2','Jun W3','Jun W4','Jul W1','Jul W2','Jul W3','Jul W4','Aug W1','Aug W2','Aug W3','Aug W4','Sep W1','Sep W2','Sep W3','Sep W4','Oct W1','Oct W2','Oct W3','Oct W4','Nov W1','Nov W2','Nov W3','Nov W4','Dec W1','Dec W2','Dec W3','Dec W4','Jan W1','Jan W2','Jan W3','Jan W4','Feb W1','Feb W2','Feb W3','Feb W4','Mar W1','Mar W2','Mar W3','Mar W4'];
const MONTHS=['Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'];
const CAL_HEADERS=['area','machineNo','gaugeId','certificateNo','gaugeDescription','range','workRange','lc','errorPercent','calibrationDate','dueDate','error %','certificateFileName'];
const PAT_HEADERS=['Machine','Sl.No','Check Points','Checking Method',...WEEKS];
const state={calibration:[],patrolling:[],filteredCal:[],filteredPat:[],calPage:1,patPage:1,pageSize:50,user:null};
let showAllWeeks=false, fb=null;
const isFirebaseConfigured = firebaseConfig.apiKey && !firebaseConfig.apiKey.includes('REPLACE');
if(isFirebaseConfigured){const app=initializeApp(firebaseConfig);fb={auth:getAuth(app),db:getFirestore(app),storage:getStorage(app)};}

const $=id=>document.getElementById(id);
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function log(s){$('validationLog').textContent=new Date().toLocaleString()+"\n"+s+"\n\n"+$('validationLog').textContent}
function pct(n,d){return d?Math.round(n/d*100):0}
function uniq(a){return[...new Set(a.filter(Boolean))].sort()}
function parseDate(v){if(!v)return null;if(/^\d{2}-\d{2}-\d{4}$/.test(v)){let[d,m,y]=v.split('-');return new Date(`${y}-${m}-${d}`)}let d=new Date(v);return isNaN(d)?null:d}
function fmt(v){let d=parseDate(v);return d?d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):''}
function debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}

async function loadJson(p){try{let r=await fetch(p,{cache:'no-store'});return r.ok?await r.json():[]}catch(e){return[]}}
async function loadFirestoreCollection(name){if(!fb||!state.user)return null;let snap=await getDocs(collection(fb.db,name));return snap.docs.map(d=>d.data())}
async function loadData(){let fromFirebase=false;try{if(fb&&state.user){let cal=await loadFirestoreCollection('calibration');let pat=await loadFirestoreCollection('patrolling');if(cal?.length||pat?.length){state.calibration=(cal||[]).map(normCal);state.patrolling=(pat||[]).map(normPat);fromFirebase=true}}}catch(e){log('Firestore load failed, using JSON fallback: '+e.message)}if(!fromFirebase){let [cal,pat]=await Promise.all([loadJson('data/calibration.json'),loadJson('data/patrolling.json')]);state.calibration=cal.map(normCal);state.patrolling=pat.map(normPat)}state.filteredCal=state.calibration;state.filteredPat=state.patrolling;$('dataMode').textContent=fromFirebase?'Live Firebase Firestore':'GitHub JSON fallback';$('firebaseStatus').textContent=isFirebaseConfigured?'Firebase configured':'Firebase config pending';renderAll()}
function normCal(r){let due=parseDate(r.dueDate);let daysLeft=due?Math.ceil((due-new Date())/86400000):null;let status=daysLeft!==null&&daysLeft<0?'Overdue':daysLeft!==null&&daysLeft<=30?'Due Soon':'Valid';return{...r,status,daysLeft}}
function normPat(r){let o={Machine:r.Machine||r.machine||'', 'Sl.No':r['Sl.No']||r.slNo||'', 'Check Points':r['Check Points']||r['Check Point']||r.checkPoint||'', 'Checking Method':r['Checking Method']||r.checkingMethod||''};WEEKS.forEach(w=>o[w]=(r[w]||'').toString().trim().toUpperCase());return o}
function latestStatus(r,wks=WEEKS){let lastWeek='',lastValue='';for(let i=wks.length-1;i>=0;i--){let v=r[wks[i]];if(v){lastWeek=wks[i];lastValue=v;break}}let lastX='',okAfterX='',prevO='';for(let i=0;i<wks.length;i++){let v=r[wks[i]];if(v==='O'&&!lastX)prevO=wks[i];if(v==='X'){lastX=wks[i];okAfterX=''}if(lastX&&v==='O')okAfterX=wks[i]}let status=!lastValue?'NOT_DONE':lastValue==='X'?'OPEN_X':'OK';return{status,lastWeek,lastValue,lastX,okAfterX,prevO}}
function reportData(){let open=[],converted=[],notdone=[];state.patrolling.forEach(r=>{let s=latestStatus(r);if(s.status==='OPEN_X')open.push({...r,_ls:s});if(s.status==='NOT_DONE')notdone.push({...r,_ls:s});if(s.okAfterX&&s.status==='OK')converted.push({...r,_ls:s})});return{open,converted,notdone}}
function closureWeeks(x,o){let xi=WEEKS.indexOf(x),oi=WEEKS.indexOf(o);return xi>=0&&oi>=0&&oi>=xi?`${oi-xi} week(s)`:''}
function renderAll(){renderKpis();renderCalTable();renderPatHeader();renderPatTable();renderReports();renderCharts();renderTopOverdue();renderYearStrip()}
function renderKpis(){let rep=reportData(),tg=state.calibration.length,due=state.calibration.filter(x=>x.status==='Due Soon').length,ov=state.calibration.filter(x=>x.status==='Overdue').length,tm=uniq(state.patrolling.map(x=>x.Machine)).length,tc=state.patrolling.length,cc=pct(tg-ov,tg),pc=patLatestCompliance(),overall=Math.round((cc+pc)/2);let arr=[['📏','Total Gauges',tg,'Calibration records'],['⏳','Due Soon',due,'Within 30 days'],['🚨','Overdue',ov,'Need action'],['🏭','Machines',tm,'Patrolling scope'],['✅','Checkpoints',tc,'Inspection items'],['⚠️','Open NG',rep.open.length,'Latest check is X'],['📌','Not Done',rep.notdone.length,'No check entry'],['🛡️','Overall',overall+'%','Combined score']];$('dashboardKpis').innerHTML=arr.map(k=>`<div class="card kpi"><div class="icon">${k[0]}</div><h3>${k[1]}</h3><div class="value">${k[2]}</div><div class="note">${k[3]}</div></div>`).join('');$('calComplianceBadge').textContent=cc+'%';$('patComplianceBadge').textContent=pc+'%'}
function renderCalTable(){let s=(state.calPage-1)*state.pageSize,rows=state.filteredCal.slice(s,s+state.pageSize);$('calResultCount').textContent=state.filteredCal.length+' records';$('calTable').innerHTML=rows.map(r=>{let b=r.status==='Overdue'?'danger-b':r.status==='Due Soon'?'warn':'ok';let cert=r.certificateUrl||(r.certificateFileName?`certificates/${r.certificateFileName}`:'');return`<tr><td>${esc(r.area)}</td><td><b>${esc(r.machineNo)}</b></td><td><b>${esc(r.gaugeId)}</b></td><td>${esc(r.certificateNo)}</td><td>${esc(r.gaugeDescription)}</td><td>${esc(r.range)}</td><td>${esc(r.workRange)}</td><td>${esc(r.lc)}</td><td>${esc(r.errorPercent)}</td><td>${fmt(r.calibrationDate)}</td><td>${fmt(r.dueDate)}</td><td>${esc(r['error %']||r.errorPct||'')}</td><td><span class="badge ${b}">${r.status}</span></td><td>${cert?`<a href="${cert}" target="_blank">View PDF</a>`:'NA'}</td></tr>`}).join('');pager('cal',state.filteredCal.length,state.calPage)}
function renderPatHeader(){let cw=showAllWeeks?WEEKS:WEEKS.slice(0,12);$('patHead').innerHTML=`<tr><th>Machine</th><th>Sl.No</th><th>Check Points</th><th>Checking Method</th>${cw.map(w=>`<th>${w}</th>`).join('')}<th>Latest Status</th><th>Last Week</th></tr>`}
function renderPatTable(){let s=(state.patPage-1)*state.pageSize,rows=state.filteredPat.slice(s,s+state.pageSize),cw=showAllWeeks?WEEKS:WEEKS.slice(0,12);$('patResultCount').textContent=state.filteredPat.length+' records';$('patTable').innerHTML=rows.map(r=>{let ls=latestStatus(r),b=ls.status==='OPEN_X'?'danger-b':ls.status==='OK'?'ok':'neutral',label=ls.status==='OPEN_X'?'ABNORMAL':ls.status==='OK'?'OKIE':'NOT DONE';return`<tr><td><b>${esc(r.Machine)}</b></td><td>${esc(r['Sl.No'])}</td><td>${esc(r['Check Points'])}</td><td>${esc(r['Checking Method'])}</td>${cw.map(w=>weekCell(r[w])).join('')}<td><span class="badge ${b}">${label}</span></td><td>${esc(ls.lastWeek||'-')}</td></tr>`}).join('');pager('pat',state.filteredPat.length,state.patPage)}
function renderReports(){let rep=reportData();$('openAbnCount').textContent=rep.open.length+' open';$('conversionCount').textContent=rep.converted.length+' closed';$('notDoneCount').textContent=rep.notdone.length+' not done';$('openAbnormalTable').innerHTML=rep.open.length?rep.open.map(r=>`<tr><td><b>${esc(r.Machine)}</b></td><td>${esc(r['Sl.No'])}</td><td>${esc(r['Check Points'])}</td><td>${esc(r['Checking Method'])}</td><td>${esc(r._ls.lastWeek)}</td><td><span class="badge danger-b">X</span></td><td>${esc(r._ls.prevO||'-')}</td></tr>`).join(''):'<tr><td colspan="7">No open abnormal.</td></tr>';$('conversionTable').innerHTML=rep.converted.length?rep.converted.map(r=>`<tr><td><b>${esc(r.Machine)}</b></td><td>${esc(r['Sl.No'])}</td><td>${esc(r['Check Points'])}</td><td><span class="badge danger-b">${esc(r._ls.lastX)}</span></td><td><span class="badge ok">${esc(r._ls.okAfterX)}</span></td><td>${closureWeeks(r._ls.lastX,r._ls.okAfterX)}</td><td><span class="badge ok">OKIE</span></td></tr>`).join(''):'<tr><td colspan="7">No abnormal to OKIE conversion.</td></tr>';$('notDoneTable').innerHTML=rep.notdone.length?rep.notdone.map(r=>`<tr><td><b>${esc(r.Machine)}</b></td><td>${esc(r['Sl.No'])}</td><td>${esc(r['Check Points'])}</td><td>${esc(r['Checking Method'])}</td><td><span class="badge neutral">NOT DONE</span></td><td>Complete patrolling entry and update O / X</td></tr>`).join(''):'<tr><td colspan="6">No not-done checkpoints.</td></tr>';renderNgVisuals()}
function renderNgVisuals(){let rep=reportData(),ok=state.patrolling.filter(r=>latestStatus(r).status==='OK').length;let tiles=[['🚨','Open NG Points',rep.open.length,'Latest check is X','danger'],['✅','Converted to OKIE',rep.converted.length,'Earlier X closed by O','oktile'],['📌','Not Done Points',rep.notdone.length,'No weekly check entry','warnTile'],['🛡️','Latest OK Points',ok,'Current healthy points','oktile']];$('ngSummaryTiles').innerHTML=tiles.map(x=>`<div class="ng-tile ${x[4]}"><div class="ng-icon">${x[0]}</div><div class="ng-title">${x[1]}</div><div class="ng-value">${x[2]}</div><div class="ng-caption">${x[3]}</div></div>`).join('');let items=rep.open.slice(0,6);$('topIssueCards').innerHTML=items.length?items.map(r=>`<div class="issue-card"><h3>${esc(r['Check Points'])}</h3><p>${esc(r['Checking Method'])}</p><div class="issue-meta"><span>${esc(r.Machine)}</span><span>Sl.No ${esc(r['Sl.No'])}</span><span>${esc(r._ls.lastWeek)}</span></div></div>`).join(''):'<div class="issue-card"><h3>No open NG points</h3><p>All latest patrolling checks are OKIE or not done.</p></div>'}
function renderYearStrip(){let data=monthlyPat();$('patYearStrip').innerHTML=data.map(d=>{let cls=d.value>=95?'good':d.value>=80?'medium':'bad';return`<div class="month-box ${cls}"><div class="m">${d.label}</div><div class="p">${d.value}%</div></div>`}).join('')}
function renderCharts(){bar('calMonthlyChart',monthlyCal(),'#2563eb','%');bar('patMonthlyChart',monthlyPat(),'#16a34a','%');bar('topIssuesChart',topOpenIssues(),'#dc2626','');bar('areaChart',areaComp(),'#8b5cf6','%')}
function renderTopOverdue(){let rows=state.calibration.filter(x=>x.status==='Overdue').sort((a,b)=>(a.daysLeft||0)-(b.daysLeft||0)).slice(0,8);$('topOverdueTable').innerHTML=rows.length?rows.map(r=>`<tr><td><b>${esc(r.gaugeId)}</b></td><td>${esc(r.machineNo)}</td><td><span class="badge danger-b">${Math.abs(r.daysLeft)} days</span></td></tr>`).join(''):'<tr><td>No overdue gauges</td></tr>'}
function monthlyCal(){let g={};state.calibration.forEach(r=>{let d=parseDate(r.dueDate);if(!d)return;let k=d.toLocaleString('en',{month:'short'});g[k]||={t:0,o:0};g[k].t++;if(r.status!=='Overdue')g[k].o++});return Object.entries(g).map(([label,v])=>({label,value:pct(v.o,v.t)}))}
function monthlyPat(){return MONTHS.map(m=>({label:m,value:calcPatByMonth(WEEKS.filter(w=>w.startsWith(m)))}))}
function topOpenIssues(){let map={};reportData().open.forEach(r=>{let key=r['Check Points'].slice(0,32);map[key]=(map[key]||0)+1});return Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,value])=>({label,value}))}
function areaComp(){let m={};state.calibration.forEach(r=>{m[r.area]||={t:0,o:0};m[r.area].t++;if(r.status!=='Overdue')m[r.area].o++});return Object.entries(m).map(([label,v])=>({label,value:pct(v.o,v.t)}))}
function bar(id,data,color,suffix){let c=$(id);if(!c)return;let ctx=c.getContext('2d'),dpr=devicePixelRatio||1,rect=c.getBoundingClientRect();c.width=rect.width*dpr;c.height=rect.height*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,rect.width,rect.height);if(!data.length){ctx.fillStyle='#64748b';ctx.fillText('No data available',20,40);return}let pad=40,max=Math.max(...data.map(d=>d.value),1),bw=Math.max(18,(rect.width-pad*2)/data.length-12);data.forEach((d,i)=>{let x=pad+i*((rect.width-pad*2)/data.length)+6,h=(rect.height-90)*(d.value/max),y=rect.height-50-h;ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,bw,h,8);ctx.fill();ctx.fillStyle='#334155';ctx.font='11px Segoe UI';ctx.textAlign='center';ctx.fillText(String(d.label).slice(0,18),x+bw/2,rect.height-24);ctx.fillStyle='#0f172a';ctx.font='bold 12px Segoe UI';ctx.fillText(d.value+suffix,x+bw/2,Math.max(14,y-7))})}
function patLatestCompliance(){let ok=0,total=0;state.patrolling.forEach(r=>{let s=latestStatus(r);if(s.status!=='NOT_DONE'){total++;if(s.status==='OK')ok++}});return pct(ok,total)}
function calcPatByMonth(wks){let ok=0,total=0;state.patrolling.forEach(r=>{let s=latestStatus(r,wks);if(s.status!=='NOT_DONE'){total++;if(s.status==='OK')ok++}});return pct(ok,total)}
function weekCell(v){return`<td class="${v==='O'?'week-ok':v==='X'?'week-x':'week-blank'}">${v||'-'}</td>`}
function pager(p,total,page){let pages=Math.max(1,Math.ceil(total/state.pageSize));$(p+'PageInfo').textContent=`Page ${page} / ${pages}`;$(p+'Prev').disabled=page<=1;$(p+'Next').disabled=page>=pages}
function csvToObjects(text){let rows=[],row=[],field='',quote=false;for(let i=0;i<text.length;i++){let c=text[i],n=text[i+1];if(c==='"'&&quote&&n==='"'){field+='"';i++}else if(c==='"'){quote=!quote}else if(c===','&&!quote){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(field);field='';if(row.some(x=>x!==''))rows.push(row);row=[]}else field+=c}if(field||row.length){row.push(field);rows.push(row)}let h=rows.shift().map(x=>x.trim().replace(/^\ufeff/,''));return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]||'').trim()]))) }
function validate(rows,req,name){if(!rows.length)return{name,ok:false,message:name+' upload rejected. No data rows.'};let miss=req.filter(c=>!Object.keys(rows[0]).includes(c));return miss.length?{ok:false,message:name+' missing columns: '+miss.join(', ')}:{ok:true,message:name+' upload OK. Rows: '+rows.length}}
async function handleUpload(e,type){let file=e.target.files[0];if(!file)return;let text=await file.text(),rows=file.name.toLowerCase().endsWith('.json')?JSON.parse(text):csvToObjects(text);let res=type==='cal'?validate(rows,CAL_HEADERS,'Calibration'):validate(rows,['Machine','Sl.No','Check Points','Checking Method'],'Patrolling');log(res.message);if(!res.ok)return;if(type==='cal'){state.calibration=rows.map(normCal);$('calUploadStatus').textContent=rows.length+' loaded'}else{state.patrolling=rows.map(normPat);$('patUploadStatus').textContent=rows.length+' loaded'}state.filteredCal=state.calibration;state.filteredPat=state.patrolling;renderAll()}
async function syncCollection(name,rows,keyFn){if(!fb||!state.user){log('Login and Firebase config required.');return}let count=0;for(let i=0;i<rows.length;i+=450){let batch=writeBatch(fb.db);rows.slice(i,i+450).forEach(r=>batch.set(doc(fb.db,name,keyFn(r)),{...r,updatedAt:serverTimestamp(),updatedBy:state.user.email},{merge:true}));await batch.commit();count+=rows.slice(i,i+450).length;log(`Synced ${count}/${rows.length} to ${name}`)}await addDoc(collection(fb.db,'auditLogs'),{action:'bulkSync',collection:name,count:rows.length,user:state.user.email,createdAt:serverTimestamp()});}
async function uploadCertificates(){if(!fb||!state.user){log('Login and Firebase config required.');return}let files=[...$('certUpload').files];for(let f of files){let fileRef=ref(fb.storage,'certificates/'+f.name);await uploadBytes(fileRef,f);let url=await getDownloadURL(fileRef);log('Uploaded '+f.name+' => '+url)} }
function downloadText(n,t){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:'text/plain'}));a.download=n;a.click();URL.revokeObjectURL(a.href)}
function applyCalFilters(){let g=$('gaugeSearch').value.toLowerCase(),m=$('machineSearchCal').value.toLowerCase(),a=$('areaSearch').value.toLowerCase(),c=$('certificateSearch').value.toLowerCase(),s=$('statusFilter').value;state.filteredCal=state.calibration.filter(r=>(!g||(`${r.gaugeId} ${r.gaugeDescription}`).toLowerCase().includes(g))&&(!m||String(r.machineNo).toLowerCase().includes(m))&&(!a||String(r.area).toLowerCase().includes(a))&&(!c||String(r.certificateNo).toLowerCase().includes(c))&&(!s||r.status===s));state.calPage=1;renderAll()}
function applyPatFilters(){let m=$('machineSearchPat').value.toLowerCase(),cp=$('checkpointSearch').value.toLowerCase(),st=$('patStatusFilter').value,mo=$('monthFilter').value,wk=mo?WEEKS.filter(w=>w.startsWith(mo)):WEEKS;state.filteredPat=state.patrolling.filter(r=>{let ls=latestStatus(r,wk);return(!m||r.Machine.toLowerCase().includes(m))&&(!cp||r['Check Points'].toLowerCase().includes(cp))&&(!st||ls.status===st)});state.patPage=1;renderAll()}

function jumpToTab(tabId){let btn=[...document.querySelectorAll('.tab[data-tab]')].find(x=>x.dataset.tab===tabId);if(btn)btn.click();}
function setupDashboardCards(){document.querySelectorAll('.dash-tab-card[data-jump]').forEach(c=>c.onclick=()=>jumpToTab(c.dataset.jump));document.querySelectorAll('.dash-tab-card[data-scroll]').forEach(c=>c.onclick=()=>{let el=document.getElementById(c.dataset.scroll);if(el)el.scrollIntoView({behavior:'smooth',block:'center'});});}
function setup(){document.querySelectorAll('.tab[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');setTimeout(renderCharts,80)});['gaugeSearch','machineSearchCal','areaSearch','certificateSearch','statusFilter'].forEach(id=>$(id).addEventListener('input',debounce(applyCalFilters,200)));['machineSearchPat','checkpointSearch','patStatusFilter','monthFilter'].forEach(id=>$(id).addEventListener('input',debounce(applyPatFilters,200)));MONTHS.forEach(m=>$('monthFilter').insertAdjacentHTML('beforeend',`<option>${m}</option>`));$('calPrev').onclick=()=>{state.calPage--;renderCalTable()};$('calNext').onclick=()=>{state.calPage++;renderCalTable()};$('patPrev').onclick=()=>{state.patPage--;renderPatTable()};$('patNext').onclick=()=>{state.patPage++;renderPatTable()};$('toggleWeeks').onclick=()=>{showAllWeeks=!showAllWeeks;renderPatHeader();renderPatTable()};$('calUpload').onchange=e=>handleUpload(e,'cal');$('patUpload').onchange=e=>handleUpload(e,'pat');$('exportCalJson').onclick=()=>downloadText('calibration.json',JSON.stringify(state.calibration,null,2));$('exportPatJson').onclick=()=>downloadText('patrolling.json',JSON.stringify(state.patrolling,null,2));$('downloadCalCsv').onclick=()=>downloadText('calibration_template.csv',CAL_HEADERS.join(',')+'\n');$('downloadPatCsv').onclick=()=>downloadText('patrolling_template.csv',PAT_HEADERS.join(',')+'\n');$('syncCalFirestore').onclick=()=>syncCollection('calibration',state.calibration,r=>String(r.gaugeId||crypto.randomUUID()).replaceAll('/','_'));$('syncPatFirestore').onclick=()=>syncCollection('patrolling',state.patrolling,r=>String((r.Machine||'M')+'_'+(r['Sl.No']||crypto.randomUUID())).replaceAll('/','_'));$('uploadCerts').onclick=uploadCertificates;$('loginBtn').onclick=async()=>{if(!fb){log('Firebase config not filled.');return}await signInWithEmailAndPassword(fb.auth,$('email').value,$('password').value)};$('logoutBtn').onclick=async()=>{if(fb)await signOut(fb.auth)};if(fb){onAuthStateChanged(fb.auth,async u=>{state.user=u;$('userBadge').textContent=u?'Logged in: '+u.email:'Not logged in';await loadData()})}else{loadData()}}
setupDashboardCards();
window.addEventListener('resize',debounce(renderCharts,150));setup();
