
const WEEKS = ["Apr W1", "Apr W2", "Apr W3", "Apr W4", "May W1", "May W2", "May W3", "May W4", "Jun W1", "Jun W2", "Jun W3", "Jun W4", "Jul W1", "Jul W2", "Jul W3", "Jul W4", "Aug W1", "Aug W2", "Aug W3", "Aug W4", "Sep W1", "Sep W2", "Sep W3", "Sep W4", "Oct W1", "Oct W2", "Oct W3", "Oct W4", "Nov W1", "Nov W2", "Nov W3", "Nov W4", "Dec W1", "Dec W2", "Dec W3", "Dec W4", "Jan W1", "Jan W2", "Jan W3", "Jan W4", "Feb W1", "Feb W2", "Feb W3", "Feb W4", "Mar W1", "Mar W2", "Mar W3", "Mar W4"];
const MONTHS = ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"];
let cal=[], pat=[], fcal=[], fpat=[], calPage=1, patPage=1, pageSize=50, showAllWeeks=false;
const $=id=>document.getElementById(id);
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function pct(n,d){return d?Math.round(n/d*100):0}
function parseDate(v){if(!v)return null;if(/^\d{2}-\d{2}-\d{4}$/.test(v)){let[d,m,y]=v.split('-');return new Date(`${y}-${m}-${d}`)}let d=new Date(v);return isNaN(d)?null:d}
function fmt(v){let d=parseDate(v);return d?d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):''}
function normCal(r){let due=parseDate(r.dueDate),days=due?Math.ceil((due-new Date())/86400000):null;let status=days!==null&&days<0?'Overdue':days!==null&&days<=30?'Due Soon':'Valid';return {...r,status,daysLeft:days}}
function normPat(r){let o={Machine:r.Machine||'', 'Sl.No':r['Sl.No']||'', 'Check Points':r['Check Points']||'', 'Checking Method':r['Checking Method']||''};WEEKS.forEach(w=>o[w]=(r[w]||'').toString().trim().toUpperCase());return o}
function latest(r,wks=WEEKS){let lastWeek='',lastValue='';for(let i=wks.length-1;i>=0;i--){let v=r[wks[i]];if(v){lastWeek=wks[i];lastValue=v;break}}let lastX='',okAfterX='',prevO='';for(let w of wks){let v=r[w];if(v==='O'&&!lastX)prevO=w;if(v==='X'){lastX=w;okAfterX=''}if(lastX&&v==='O')okAfterX=w}return {status:!lastValue?'NOT_DONE':lastValue==='X'?'OPEN_X':'OK',lastWeek,lastValue,lastX,okAfterX,prevO}}
function report(){let open=[],converted=[],notdone=[];pat.forEach(r=>{let l=latest(r);if(l.status==='OPEN_X')open.push({...r,_l:l});if(l.status==='NOT_DONE')notdone.push({...r,_l:l});if(l.okAfterX&&l.status==='OK')converted.push({...r,_l:l})});return {open,converted,notdone}}
function switchTab(id){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));$(id).classList.add('active');document.querySelector(`[data-tab="${id}"]`)?.classList.add('active');setTimeout(renderCharts,80)}
document.querySelectorAll('.nav button[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
async function init(){let [cr,pr]=await Promise.all([fetch('data/calibration.json').then(r=>r.json()).catch(()=>[]),fetch('data/patrolling.json').then(r=>r.json()).catch(()=>[])]);cal=cr.map(normCal);pat=pr.map(normPat);fcal=cal;fpat=pat;setup();renderAll()}
function setup(){['gaugeSearch','machineSearchCal','areaSearch','certSearch','statusFilter'].forEach(id=>$(id)?.addEventListener('input',filterCal));['machineSearchPat','checkpointSearch','patStatusFilter','monthFilter'].forEach(id=>$(id)?.addEventListener('input',filterPat));MONTHS.forEach(m=>$('monthFilter').insertAdjacentHTML('beforeend',`<option>${m}</option>`));$('toggleWeeks').onclick=()=>{showAllWeeks=!showAllWeeks;renderPat()};$('calPrev').onclick=()=>{calPage--;renderCal()};$('calNext').onclick=()=>{calPage++;renderCal()};$('patPrev').onclick=()=>{patPage--;renderPat()};$('patNext').onclick=()=>{patPage++;renderPat()};$('calUpload').onchange=e=>bulk(e,'cal');$('patUpload').onchange=e=>bulk(e,'pat');$('exportCal').onclick=()=>download('calibration.json',JSON.stringify(cal,null,2));$('exportPat').onclick=()=>download('patrolling.json',JSON.stringify(pat,null,2))}
function renderAll(){renderKpis();renderCal();renderPat();renderReports();renderCharts();renderYear()}
function renderKpis(){let r=report(),ok=pat.filter(x=>latest(x).status==='OK').length,tm=new Set(pat.map(x=>x.Machine)).size,cc=pct(cal.length-cal.filter(x=>x.status==='Overdue').length,cal.length),pc=pct(ok,pat.length-r.notdone.length),overall=Math.round((cc+pc)/2);let data=[['📏','Total Gauges',cal.length,'Calibration records'],['⏳','Due Soon',cal.filter(x=>x.status==='Due Soon').length,'Within 30 days'],['🚨','Overdue',cal.filter(x=>x.status==='Overdue').length,'Need action'],['🏭','Machines',tm,'Patrolling scope'],['✅','Checkpoints',pat.length,'Inspection items'],['⚠️','Open Abnormal',r.open.length,'Latest check is X'],['📌','Not Done',r.notdone.length,'No check entered'],['🛡️','Overall',overall+'%','Combined score']];$('kpis').innerHTML=data.map(k=>`<div class="card kpi"><div class="icon">${k[0]}</div><h3>${k[1]}</h3><div class="value">${k[2]}</div><div class="note">${k[3]}</div></div>`).join('')}
function renderCal(){let rows=fcal.slice((calPage-1)*pageSize,calPage*pageSize);$('calCount').textContent=fcal.length+' records';$('calTable').innerHTML=rows.map(r=>`<tr><td>${esc(r.area)}</td><td><b>${esc(r.machineNo)}</b></td><td><b>${esc(r.gaugeId)}</b></td><td>${esc(r.certificateNo)}</td><td>${esc(r.gaugeDescription)}</td><td>${esc(r.range)}</td><td>${esc(r.workRange)}</td><td>${esc(r.lc)}</td><td>${esc(r.errorPercent)}</td><td>${fmt(r.calibrationDate)}</td><td>${fmt(r.dueDate)}</td><td>${esc(r['error %']||'')}</td><td><span class="badge ${r.status==='Overdue'?'bad':r.status==='Due Soon'?'warn':'ok'}">${r.status}</span></td><td><span class="badge neutral">${r.certificateFileName?'PDF':'NA'}</span></td></tr>`).join('');pager('cal',fcal.length,calPage)}
function renderPat(){let cw=showAllWeeks?WEEKS:WEEKS.slice(0,13);let rows=fpat.slice((patPage-1)*pageSize,patPage*pageSize);$('patCount').textContent=fpat.length+' records';$('patHead').innerHTML=`<tr><th>Machine</th><th>Sl.No</th><th>Check Points</th><th>Checking Method</th>${cw.map(w=>`<th>${w}</th>`).join('')}<th>Latest Status</th><th>Last Week</th></tr>`;$('patTable').innerHTML=rows.map(r=>{let l=latest(r),label=l.status==='OPEN_X'?'ABNORMAL':l.status==='OK'?'OKIE':'NOT DONE';return `<tr><td><b>${esc(r.Machine)}</b></td><td>${esc(r['Sl.No'])}</td><td>${esc(r['Check Points'])}</td><td>${esc(r['Checking Method'])}</td>${cw.map(w=>`<td class="${r[w]==='X'?'week-x':r[w]==='O'?'week-ok':'week-blank'}">${r[w]||'-'}</td>`).join('')}<td><span class="badge ${l.status==='OPEN_X'?'bad':l.status==='OK'?'ok':'neutral'}">${label}</span></td><td>${l.lastWeek||'-'}</td></tr>`}).join('');pager('pat',fpat.length,patPage)}
function renderReports(){let r=report();$('openCount').textContent=r.open.length+' open';$('convCount').textContent=r.converted.length+' closed';$('notDoneCount').textContent=r.notdone.length+' not done';$('openTable').innerHTML=r.open.length?r.open.map(x=>`<tr><td><b>${esc(x.Machine)}</b></td><td>${esc(x['Sl.No'])}</td><td>${esc(x['Check Points'])}</td><td>${esc(x['Checking Method'])}</td><td>${x._l.lastWeek}</td><td><span class="badge bad">X</span></td><td>${x._l.prevO||'-'}</td><td>40 week(s)</td></tr>`).join(''):'<tr><td colspan="8">No open abnormal.</td></tr>';$('convTable').innerHTML=r.converted.length?r.converted.map(x=>`<tr><td><b>${x.Machine}</b></td><td>${x['Sl.No']}</td><td>${esc(x['Check Points'])}</td><td><span class="badge bad">${x._l.lastX}</span></td><td><span class="badge ok">${x._l.okAfterX}</span></td><td>1 week(s)</td><td><span class="badge ok">OKIE</span></td></tr>`).join(''):'<tr><td colspan="7">No conversion.</td></tr>';$('notDoneTable').innerHTML=r.notdone.length?r.notdone.map(x=>`<tr><td><b>${x.Machine}</b></td><td>${x['Sl.No']}</td><td>${esc(x['Check Points'])}</td><td>${x['Checking Method']}</td><td><span class="badge neutral">NOT DONE</span></td><td>Complete patrolling entry</td></tr>`).join(''):'<tr><td colspan="6">No not-done checkpoints.</td></tr>';let ok=pat.filter(x=>latest(x).status==='OK').length;$('ngtiles').innerHTML=[['🚨','Open NG Points',r.open.length,'Latest check is X','red'],['✅','Converted to OKIE',r.converted.length,'Earlier X closed by O','green'],['📌','Not Done Points',r.notdone.length,'No weekly check entry','yellow'],['🛡️','Latest OK Points',ok,'Current healthy points','green']].map(x=>`<div class="ngtile ${x[4]}"><div class="nicon">${x[0]}</div><h3>${x[1]}</h3><div class="num">${x[2]}</div><div class="sub">${x[3]}</div></div>`).join('');$('issueCards').innerHTML=r.open.slice(0,6).map(x=>`<div class="issue-card"><h4>${esc(x['Check Points'])}</h4><small>${esc(x['Checking Method'])}</small><div class="chips"><span class="chip">${x.Machine}</span><span class="chip">Sl.No ${x['Sl.No']}</span><span class="chip">${x._l.lastWeek}</span></div></div>`).join('')}
function renderYear(){let data=MONTHS.map(m=>{let w=WEEKS.filter(x=>x.startsWith(m)),ok=0,total=0;pat.forEach(r=>{let l=latest(r,w);if(l.status!=='NOT_DONE'){total++;if(l.status==='OK')ok++}});return {label:m,val:pct(ok,total)}});$('yearStrip').innerHTML=data.map(d=>`<div class="month-box ${d.val>=95?'good':d.val>=80?'medium':'bad'}"><div class="m">${d.label}</div><div class="p">${d.val}%</div></div>`).join('')}
function renderCharts(){bar('calChart',[{label:'Dec',value:100}],'#2863e6','%');let data=MONTHS.map(m=>{let w=WEEKS.filter(x=>x.startsWith(m)),ok=0,total=0;pat.forEach(r=>{let l=latest(r,w);if(l.status!=='NOT_DONE'){total++;if(l.status==='OK')ok++}});return {label:m,value:pct(ok,total)}});bar('patChart',data,'#16a34a','%');let map={};report().open.forEach(x=>{let k=x['Check Points'].slice(0,18);map[k]=(map[k]||0)+1});bar('ngChart',Object.entries(map).slice(0,8).map(([label,value])=>({label,value})),'#dc2626','')}
function bar(id,data,color,suffix){let c=$(id);if(!c)return;let ctx=c.getContext('2d'),r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=r.width*dpr;c.height=r.height*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,r.width,r.height);let max=Math.max(...data.map(x=>x.value),1),bw=Math.max(18,(r.width-80)/Math.max(data.length,1)-10);data.forEach((d,i)=>{let x=40+i*((r.width-80)/data.length)+5,h=(r.height-70)*d.value/max,y=r.height-40-h;ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,bw,h,8);ctx.fill();ctx.fillStyle='#172033';ctx.font='bold 12px Segoe UI';ctx.textAlign='center';ctx.fillText(d.value+suffix,x+bw/2,Math.max(14,y-8));ctx.fillStyle='#334155';ctx.font='11px Segoe UI';ctx.fillText(d.label,x+bw/2,r.height-18)})}
function pager(prefix,total,page){let pages=Math.max(1,Math.ceil(total/pageSize));$(prefix+'Page').textContent=`Page ${page} / ${pages}`;$(prefix+'Prev').disabled=page<=1;$(prefix+'Next').disabled=page>=pages}
function filterCal(){let g=$('gaugeSearch').value.toLowerCase(),m=$('machineSearchCal').value.toLowerCase(),a=$('areaSearch').value.toLowerCase(),c=$('certSearch').value.toLowerCase(),s=$('statusFilter').value;fcal=cal.filter(r=>(!g||(r.gaugeId+' '+r.gaugeDescription).toLowerCase().includes(g))&&(!m||r.machineNo.toLowerCase().includes(m))&&(!a||r.area.toLowerCase().includes(a))&&(!c||r.certificateNo.toLowerCase().includes(c))&&(!s||r.status===s));calPage=1;renderCal()}
function filterPat(){let m=$('machineSearchPat').value.toLowerCase(),cp=$('checkpointSearch').value.toLowerCase(),st=$('patStatusFilter').value,mo=$('monthFilter').value,wks=mo?WEEKS.filter(w=>w.startsWith(mo)):WEEKS;fpat=pat.filter(r=>{let l=latest(r,wks);return (!m||r.Machine.toLowerCase().includes(m))&&(!cp||r['Check Points'].toLowerCase().includes(cp))&&(!st||l.status===st)});patPage=1;renderPat()}
function csvToObjects(text){let rows=[],row=[],field='',quote=false;for(let i=0;i<text.length;i++){let c=text[i],n=text[i+1];if(c==='"'&&quote&&n==='"'){field+='"';i++}else if(c==='"'){quote=!quote}else if(c===','&&!quote){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(field);field='';if(row.some(x=>x!==''))rows.push(row);row=[]}else field+=c}if(field||row.length){row.push(field);rows.push(row)}let h=rows.shift().map(x=>x.trim().replace(/^\ufeff/,''));return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]||'').trim()]))) }
function log(s){$('uploadLog').textContent=new Date().toLocaleString()+'\n'+s+'\n\n'+$('uploadLog').textContent}
async function bulk(e,type){let file=e.target.files[0];if(!file)return;try{let text=await file.text();let rows=file.name.toLowerCase().endsWith('.json')?JSON.parse(text):csvToObjects(text);if(type==='cal'){cal=rows.map(normCal);fcal=cal;$('calUploadStatus').textContent=rows.length+' loaded';log('Calibration upload OK: '+rows.length+' rows')}else{pat=rows.map(normPat);fpat=pat;$('patUploadStatus').textContent=rows.length+' loaded';log('Patrolling upload OK: '+rows.length+' rows')}renderAll()}catch(err){log('Upload failed: '+err.message)}}
function download(name,text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
window.addEventListener('resize',()=>renderCharts());init();
